pre_bump_hooks = [
    "echo {{version}}",
]

post_bump_hooks = []
tag_prefix = "v"

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = [
    { username = "dfranusic", signature = "Damir Franusic" }
]
template = "remote"
remote = "github.com"
repository = "mink-core"
owner = "link-mink"

[bump_profiles]
