/** \file
 *  This C header file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : ./mink.g
 *     -                            On : 2015-02-19 12:50:40
 *     -                 for the lexer : minkLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer minkLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pminkLexer, which is returned from a call to minkLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pminkLexer are  as follows:
 *
 *  -  void      pminkLexer->A_ROND(pminkLexer)
 *  -  void      pminkLexer->STAR(pminkLexer)
 *  -  void      pminkLexer->ASSIGN_OP(pminkLexer)
 *  -  void      pminkLexer->BOOLEAN_LITERAL(pminkLexer)
 *  -  void      pminkLexer->TRUE_LITERAL(pminkLexer)
 *  -  void      pminkLexer->FALSE_LITERAL(pminkLexer)
 *  -  void      pminkLexer->DOT(pminkLexer)
 *  -  void      pminkLexer->DOUBLE_DOT(pminkLexer)
 *  -  void      pminkLexer->ELLIPSIS(pminkLexer)
 *  -  void      pminkLexer->APOSTROPHE(pminkLexer)
 *  -  void      pminkLexer->AMPERSAND(pminkLexer)
 *  -  void      pminkLexer->LESS_THAN(pminkLexer)
 *  -  void      pminkLexer->GREATER_THAN(pminkLexer)
 *  -  void      pminkLexer->LESS_THAN_SLASH(pminkLexer)
 *  -  void      pminkLexer->SHASH_GREATER_THEN(pminkLexer)
 *  -  void      pminkLexer->TRUE_SMALL_LITERAL(pminkLexer)
 *  -  void      pminkLexer->FALSE_SMALL_LITERAL(pminkLexer)
 *  -  void      pminkLexer->IA5_STRING_LITERAL(pminkLexer)
 *  -  void      pminkLexer->L_BRACE(pminkLexer)
 *  -  void      pminkLexer->R_BRACE(pminkLexer)
 *  -  void      pminkLexer->COMMA(pminkLexer)
 *  -  void      pminkLexer->L_PARAN(pminkLexer)
 *  -  void      pminkLexer->R_PARAN(pminkLexer)
 *  -  void      pminkLexer->MINUS(pminkLexer)
 *  -  void      pminkLexer->ENUMERATED_LITERAL(pminkLexer)
 *  -  void      pminkLexer->REAL_LITERAL(pminkLexer)
 *  -  void      pminkLexer->PLUS_INFINITY_LITERAL(pminkLexer)
 *  -  void      pminkLexer->MINUS_INFINITY_LITERAL(pminkLexer)
 *  -  void      pminkLexer->BIT_LITERAL(pminkLexer)
 *  -  void      pminkLexer->CONTAINING_LITERAL(pminkLexer)
 *  -  void      pminkLexer->OCTET_LITERAL(pminkLexer)
 *  -  void      pminkLexer->NULL_LITERAL(pminkLexer)
 *  -  void      pminkLexer->SEQUENCE_LITERAL(pminkLexer)
 *  -  void      pminkLexer->OPTIONAL_LITERAL(pminkLexer)
 *  -  void      pminkLexer->DEFAULT_LITERAL(pminkLexer)
 *  -  void      pminkLexer->COMPONENTS_LITERAL(pminkLexer)
 *  -  void      pminkLexer->OF_LITERAL(pminkLexer)
 *  -  void      pminkLexer->SET_LITERAL(pminkLexer)
 *  -  void      pminkLexer->EXCLAM(pminkLexer)
 *  -  void      pminkLexer->ALL_LITERAL(pminkLexer)
 *  -  void      pminkLexer->EXCEPT_LITERAL(pminkLexer)
 *  -  void      pminkLexer->POWER(pminkLexer)
 *  -  void      pminkLexer->PIPE(pminkLexer)
 *  -  void      pminkLexer->UNION_LITERAL(pminkLexer)
 *  -  void      pminkLexer->INTERSECTION_LITERAL(pminkLexer)
 *  -  void      pminkLexer->INCLUDES_LITERAL(pminkLexer)
 *  -  void      pminkLexer->MIN_LITERAL(pminkLexer)
 *  -  void      pminkLexer->MAX_LITERAL(pminkLexer)
 *  -  void      pminkLexer->SIZE_LITERAL(pminkLexer)
 *  -  void      pminkLexer->FROM_LITERAL(pminkLexer)
 *  -  void      pminkLexer->WITH_LITERAL(pminkLexer)
 *  -  void      pminkLexer->COMPONENT_LITERAL(pminkLexer)
 *  -  void      pminkLexer->PRESENT_LITERAL(pminkLexer)
 *  -  void      pminkLexer->ABSENT_LITERAL(pminkLexer)
 *  -  void      pminkLexer->PATTERN_LITERAL(pminkLexer)
 *  -  void      pminkLexer->TYPE_IDENTIFIER_LITERAL(pminkLexer)
 *  -  void      pminkLexer->ABSTRACT_SYNTAX_LITERAL(pminkLexer)
 *  -  void      pminkLexer->CLASS_LITERAL(pminkLexer)
 *  -  void      pminkLexer->UNIQUE_LITERAL(pminkLexer)
 *  -  void      pminkLexer->SYNTAX_LITERAL(pminkLexer)
 *  -  void      pminkLexer->L_BRACKET(pminkLexer)
 *  -  void      pminkLexer->R_BRACKET(pminkLexer)
 *  -  void      pminkLexer->INSTANCE_LITERAL(pminkLexer)
 *  -  void      pminkLexer->SEMI_COLON(pminkLexer)
 *  -  void      pminkLexer->IMPORTS_LITERAL(pminkLexer)
 *  -  void      pminkLexer->EXPORTS_LITERAL(pminkLexer)
 *  -  void      pminkLexer->EXTENSIBILITY_LITERAL(pminkLexer)
 *  -  void      pminkLexer->IMPLIED_LITERAL(pminkLexer)
 *  -  void      pminkLexer->EXPLICIT_LITERAL(pminkLexer)
 *  -  void      pminkLexer->TAGS_LITERAL(pminkLexer)
 *  -  void      pminkLexer->IMPLICIT_LITERAL(pminkLexer)
 *  -  void      pminkLexer->AUTOMATIC_LITERAL(pminkLexer)
 *  -  void      pminkLexer->DEFINITIONS_LITERAL(pminkLexer)
 *  -  void      pminkLexer->BEGIN_LITERAL(pminkLexer)
 *  -  void      pminkLexer->END_LITERAL(pminkLexer)
 *  -  void      pminkLexer->DOUBLE_L_BRACKET(pminkLexer)
 *  -  void      pminkLexer->DOUBLE_R_BRACKET(pminkLexer)
 *  -  void      pminkLexer->COLON(pminkLexer)
 *  -  void      pminkLexer->CHOICE_LITERAL(pminkLexer)
 *  -  void      pminkLexer->UNIVERSAL_LITERAL(pminkLexer)
 *  -  void      pminkLexer->APPLICATION_LITERAL(pminkLexer)
 *  -  void      pminkLexer->PRIVATE_LITERAL(pminkLexer)
 *  -  void      pminkLexer->EMBEDDED_LITERAL(pminkLexer)
 *  -  void      pminkLexer->PDV_LITERAL(pminkLexer)
 *  -  void      pminkLexer->OBJECT_LITERAL(pminkLexer)
 *  -  void      pminkLexer->IDENTIFIER_LITERAL(pminkLexer)
 *  -  void      pminkLexer->RELATIVE_OID_LITERAL(pminkLexer)
 *  -  void      pminkLexer->CHARACTER_LITERAL(pminkLexer)
 *  -  void      pminkLexer->CONSTRAINED_LITERAL(pminkLexer)
 *  -  void      pminkLexer->BY_LITERAL(pminkLexer)
 *  -  void      pminkLexer->A_ROND_DOT(pminkLexer)
 *  -  void      pminkLexer->ENCODED_LITERAL(pminkLexer)
 *  -  void      pminkLexer->CONST_LITERAL(pminkLexer)
 *  -  void      pminkLexer->SCRIPT_LITERAL(pminkLexer)
 *  -  void      pminkLexer->METHOD_LITERAL(pminkLexer)
 *  -  void      pminkLexer->PTRN_LITERAL(pminkLexer)
 *  -  void      pminkLexer->COMMENT(pminkLexer)
 *  -  void      pminkLexer->CONFIG_LITERAL(pminkLexer)
 *  -  void      pminkLexer->TYPES_LITERAL(pminkLexer)
 *  -  void      pminkLexer->EXTENSTIONENDMARKER(pminkLexer)
 *  -  void      pminkLexer->DIGIT(pminkLexer)
 *  -  void      pminkLexer->NUMBER(pminkLexer)
 *  -  void      pminkLexer->WS(pminkLexer)
 *  -  void      pminkLexer->Exponent(pminkLexer)
 *  -  void      pminkLexer->LINE_COMMENT(pminkLexer)
 *  -  void      pminkLexer->BSTRING(pminkLexer)
 *  -  void      pminkLexer->HEXDIGIT(pminkLexer)
 *  -  void      pminkLexer->HSTRING(pminkLexer)
 *  -  void      pminkLexer->CSTRING(pminkLexer)
 *  -  void      pminkLexer->REGEX(pminkLexer)
 *  -  void      pminkLexer->EscapeSequence(pminkLexer)
 *  -  void      pminkLexer->LETTER(pminkLexer)
 *  -  void      pminkLexer->JavaIDDigit(pminkLexer)
 *  -  void      pminkLexer->IDENTIFIER(pminkLexer)
 *  -  void      pminkLexer->ML_COMMENT(pminkLexer)
 *  -  void      pminkLexer->SL_COMMENT(pminkLexer)
 *  -  void      pminkLexer->Tokens(pminkLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_minkLexer_H
#define _minkLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct minkLexer_Ctx_struct minkLexer, * pminkLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for minkLexer
 */
struct minkLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mA_ROND)	(struct minkLexer_Ctx_struct * ctx);
     void (*mSTAR)	(struct minkLexer_Ctx_struct * ctx);
     void (*mASSIGN_OP)	(struct minkLexer_Ctx_struct * ctx);
     void (*mBOOLEAN_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mTRUE_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mFALSE_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mDOT)	(struct minkLexer_Ctx_struct * ctx);
     void (*mDOUBLE_DOT)	(struct minkLexer_Ctx_struct * ctx);
     void (*mELLIPSIS)	(struct minkLexer_Ctx_struct * ctx);
     void (*mAPOSTROPHE)	(struct minkLexer_Ctx_struct * ctx);
     void (*mAMPERSAND)	(struct minkLexer_Ctx_struct * ctx);
     void (*mLESS_THAN)	(struct minkLexer_Ctx_struct * ctx);
     void (*mGREATER_THAN)	(struct minkLexer_Ctx_struct * ctx);
     void (*mLESS_THAN_SLASH)	(struct minkLexer_Ctx_struct * ctx);
     void (*mSHASH_GREATER_THEN)	(struct minkLexer_Ctx_struct * ctx);
     void (*mTRUE_SMALL_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mFALSE_SMALL_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mIA5_STRING_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mL_BRACE)	(struct minkLexer_Ctx_struct * ctx);
     void (*mR_BRACE)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCOMMA)	(struct minkLexer_Ctx_struct * ctx);
     void (*mL_PARAN)	(struct minkLexer_Ctx_struct * ctx);
     void (*mR_PARAN)	(struct minkLexer_Ctx_struct * ctx);
     void (*mMINUS)	(struct minkLexer_Ctx_struct * ctx);
     void (*mENUMERATED_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mREAL_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mPLUS_INFINITY_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mMINUS_INFINITY_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mBIT_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCONTAINING_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mOCTET_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mNULL_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mSEQUENCE_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mOPTIONAL_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mDEFAULT_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCOMPONENTS_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mOF_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mSET_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mEXCLAM)	(struct minkLexer_Ctx_struct * ctx);
     void (*mALL_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mEXCEPT_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mPOWER)	(struct minkLexer_Ctx_struct * ctx);
     void (*mPIPE)	(struct minkLexer_Ctx_struct * ctx);
     void (*mUNION_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mINTERSECTION_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mINCLUDES_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mMIN_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mMAX_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mSIZE_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mFROM_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mWITH_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCOMPONENT_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mPRESENT_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mABSENT_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mPATTERN_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mTYPE_IDENTIFIER_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mABSTRACT_SYNTAX_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCLASS_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mUNIQUE_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mSYNTAX_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mL_BRACKET)	(struct minkLexer_Ctx_struct * ctx);
     void (*mR_BRACKET)	(struct minkLexer_Ctx_struct * ctx);
     void (*mINSTANCE_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mSEMI_COLON)	(struct minkLexer_Ctx_struct * ctx);
     void (*mIMPORTS_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mEXPORTS_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mEXTENSIBILITY_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mIMPLIED_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mEXPLICIT_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mTAGS_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mIMPLICIT_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mAUTOMATIC_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mDEFINITIONS_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mBEGIN_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mEND_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mDOUBLE_L_BRACKET)	(struct minkLexer_Ctx_struct * ctx);
     void (*mDOUBLE_R_BRACKET)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCOLON)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCHOICE_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mUNIVERSAL_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mAPPLICATION_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mPRIVATE_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mEMBEDDED_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mPDV_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mOBJECT_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mIDENTIFIER_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mRELATIVE_OID_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCHARACTER_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCONSTRAINED_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mBY_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mA_ROND_DOT)	(struct minkLexer_Ctx_struct * ctx);
     void (*mENCODED_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCONST_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mSCRIPT_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mMETHOD_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mPTRN_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCOMMENT)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCONFIG_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mTYPES_LITERAL)	(struct minkLexer_Ctx_struct * ctx);
     void (*mEXTENSTIONENDMARKER)	(struct minkLexer_Ctx_struct * ctx);
     void (*mDIGIT)	(struct minkLexer_Ctx_struct * ctx);
     void (*mNUMBER)	(struct minkLexer_Ctx_struct * ctx);
     void (*mWS)	(struct minkLexer_Ctx_struct * ctx);
     void (*mExponent)	(struct minkLexer_Ctx_struct * ctx);
     void (*mLINE_COMMENT)	(struct minkLexer_Ctx_struct * ctx);
     void (*mBSTRING)	(struct minkLexer_Ctx_struct * ctx);
     void (*mHEXDIGIT)	(struct minkLexer_Ctx_struct * ctx);
     void (*mHSTRING)	(struct minkLexer_Ctx_struct * ctx);
     void (*mCSTRING)	(struct minkLexer_Ctx_struct * ctx);
     void (*mREGEX)	(struct minkLexer_Ctx_struct * ctx);
     void (*mEscapeSequence)	(struct minkLexer_Ctx_struct * ctx);
     void (*mLETTER)	(struct minkLexer_Ctx_struct * ctx);
     void (*mJavaIDDigit)	(struct minkLexer_Ctx_struct * ctx);
     void (*mIDENTIFIER)	(struct minkLexer_Ctx_struct * ctx);
     void (*mML_COMMENT)	(struct minkLexer_Ctx_struct * ctx);
     void (*mSL_COMMENT)	(struct minkLexer_Ctx_struct * ctx);
     void (*mTokens)	(struct minkLexer_Ctx_struct * ctx);    const char * (*getGrammarFileName)();
    void	    (*free)   (struct minkLexer_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pminkLexer minkLexerNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pminkLexer minkLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define NOTIFIED_DAEMON      125
#define MODULE_ID      104
#define NODE_COMPONENT      117
#define SEQUENCE_LITERAL      36
#define STAR      5
#define IDENTIFIER_NODE      107
#define LETTER      144
#define RELATIVE_OID_LITERAL      90
#define ITEM_VALUE      130
#define REGEX      132
#define ABSENT_LITERAL      57
#define DEFINITION_NODE      110
#define EOF      -1
#define AUTOMATIC_LITERAL      75
#define DOUBLE_DOT      11
#define DEFAULT_LITERAL      38
#define ASSIGN_OP      6
#define IDENTIFIER_LITERAL      89
#define REAL_LITERAL      29
#define BIT_LITERAL      32
#define PATTERN_LITERAL      58
#define OCTET_LITERAL      34
#define R_PARAN      26
#define TRUE_LITERAL      8
#define CHOICE_LITERAL      82
#define APOSTROPHE      13
#define COMMENT      100
#define APPLICATION_LITERAL      84
#define FALSE_SMALL_LITERAL      20
#define TYPE_ROOT      128
#define LESS_THAN_SLASH      17
#define OPTIONAL_LITERAL      37
#define ITEM_TYPE      123
#define LINE_COMMENT      139
#define IMPLICIT_LITERAL      74
#define ITEM_ID      124
#define NUMBER      134
#define ELLIPSIS      12
#define L_BRACE      22
#define CHARACTER_LITERAL      91
#define POWER      45
#define NULL_LITERAL      35
#define SEMI_COLON      67
#define DEFINITIONS_NODE      106
#define TYPE_ITEM      127
#define UNION_LITERAL      47
#define PLUS_INFINITY_LITERAL      30
#define ABSTRACT_SYNTAX_LITERAL      60
#define EXCEPT_LITERAL      44
#define INSTANCE_LITERAL      66
#define COMPONENT_LITERAL      55
#define CONFIG_LITERAL      101
#define END_LITERAL      78
#define ENUMERATED_LITERAL      28
#define INCLUDES_LITERAL      49
#define WS      137
#define BSTRING      140
#define EMBEDDED_LITERAL      86
#define CLASS_LITERAL      61
#define DOUBLE_L_BRACKET      79
#define SCRIPT_LITERAL      97
#define SL_COMMENT      147
#define PTRN_LITERAL      99
#define LESS_THAN      15
#define JavaIDDigit      145
#define SYNTAX_LITERAL      63
#define TYPES_LITERAL      102
#define EXPORTS_LITERAL      69
#define SET_LITERAL      41
#define CSTRING      131
#define IMPORTS_NODE      112
#define BEGIN_LITERAL      77
#define ALL_LITERAL      43
#define EscapeSequence      143
#define METHOD_LITERAL      98
#define ITEM_DESC      126
#define L_BRACKET      64
#define CONFIG_ROOT      120
#define TAG_DESCRIPTOR      115
#define MODULE_VERSION      105
#define NODE_INFO      113
#define TAGS_LITERAL      73
#define Exponent      138
#define FALSE_LITERAL      9
#define PRESENT_LITERAL      56
#define DEFINITIONS_LITERAL      76
#define EXTENSIBILITY_LITERAL      70
#define OBJECT_LITERAL      88
#define EXPLICIT_LITERAL      72
#define COMPONENTS_LITERAL      39
#define NODE_NAME      119
#define EXTENSTIONENDMARKER      135
#define ML_COMMENT      146
#define TYPE_IDENTIFIER_LITERAL      59
#define A_ROND_DOT      94
#define COMMA      24
#define TRUE_SMALL_LITERAL      19
#define IDENTIFIER      133
#define ENCODED_LITERAL      95
#define BY_LITERAL      93
#define PRIVATE_LITERAL      85
#define PIPE      46
#define A_ROND      4
#define DIGIT      136
#define DOT      10
#define L_PARAN      25
#define TAG_DEFINITIONS      116
#define TYPE_NODE      109
#define UNIQUE_LITERAL      62
#define UNIVERSAL_LITERAL      83
#define MIN_LITERAL      50
#define MINUS_INFINITY_LITERAL      31
#define CONST_LITERAL      96
#define GREATER_THAN      16
#define LINE_ROOT      129
#define HSTRING      142
#define WITH_LITERAL      54
#define IMPORTS_LITERAL      68
#define AMPERSAND      14
#define SIZE_LITERAL      52
#define R_BRACE      23
#define MINUS      27
#define R_BRACKET      65
#define IMPLIED_LITERAL      71
#define FROM_LITERAL      53
#define COLON      81
#define BOOLEAN_LITERAL      7
#define PDV_LITERAL      87
#define EXPORTS_NODE      111
#define SHASH_GREATER_THEN      18
#define CONFIG_ITEM      121
#define TAG_SPECIFIC      118
#define VALUE_NODE      108
#define CONTAINING_LITERAL      33
#define EXCLAM      42
#define BODY_NODE      114
#define IA5_STRING_LITERAL      21
#define CONSTRAINED_LITERAL      92
#define CONFIG_BLOCK      122
#define INTERSECTION_LITERAL      48
#define OF_LITERAL      40
#define MODULE_ROOT      103
#define DOUBLE_R_BRACKET      80
#define MAX_LITERAL      51
#define HEXDIGIT      141
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for minkLexer
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
