name: build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install mINK dependencies
      run: sudo apt-get install gperf libcap-dev libsctp-dev libssl-dev libprocps-dev
    - id: install-boost
      uses: MarkusJx/install-boost@v2.1.0
      with:
        boost_version: 1.74.0
        platform_version: 20.04   
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: |
        CPPFLAGS=-I${{ steps.install-boost.outputs.BOOST_ROOT }}/include \
          ./configure --enable-64bit \
          --with-boost=${{ steps.install-boost.outputs.BOOST_ROOT }} \
          --enable-codegen \
          --enable-ws-single-session \
          --enable-plain-ws \
          --enable-openssl \
          --enable-jrpc \
          --enable-gdttrapc \
          --enable-sysagent
    - name: make
      run: make
